### PR TITLE
Add new kuiSideBar component and sub-component classes.

### PR DESCRIPTION
**Pull request by cjcenizal**
I added some new styles and implemented them in some places in the markup to demonstrate how to use them, but you'll need to apply them to the rest of the UI.

I also did some minor reorganization to use space more efficiently and group things a little more logically (in my opinion).

# Before

image

# After

image

### CODE REVIEW

**Comment by ppisljar** [comment]
thanks, looks much better !

i think Labels and Style (under cat axis) should also be collapsible ? (as those are meant to be advanced settings which only a few users will go after)

**Comment by ppisljar** [comment]
i agree that most of the settings at this point can go under global settings. but probably we'll want to split them out once we add more to the same category. for example if in the future we add 5 more options to the legend, we'll want to make that its own section (legend settings). 

currently i also think there is no need to add all those color options. however i would like to design our interface in a way that its straight forward where to add more options if we decide to add them. i also think its nice that the library (vislib) supports all those options so in case we decide to add them in the future its just adding them to the ui.

so to quickly list what would i like to see in this UI:
- one more collapsible level (where its clear that its sub level holding advanced settings)
- add/remove buttons on the top levels (adding value axes for example)
- form controls (..., slider, color picker, font picker)

**Comment by cjcenizal** [comment]
@ppisljar I pushed some changes to address your first 2 requests. Is your 3rd request (form controls) a blocker? If not, then it will have to wait until we have more time to assess our form components as a whole. If is a blocker then let's talk about your specific needs.

Here's what it looks like now:

image

**Comment by cjcenizal** [comment]
CCing @alt74 to keep him in the loop on any design changes. Jurgen, for context, Peter is adding some new features which requires new UI functionality in the sidebar.

**Comment by ppisljar** [comment]
@cjcenizal wow this is really great. 

forms are definitely not a blocker, i don't plan to have most of those options in when this is ready for merge (colors and fonts). in case we do leave them there they are going to be an advanced option so i don't think its necessary to add color pickers or font pickers.

**Pull request merged**
